Controllers/CounterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Conum.Services;
using Conum.ViewModels.Counter;
using Conum.Data.Models;

namespace Conum.Controllers
{
    public class CounterController : Controller
    {
        private ICounterService _service;

        public CounterController(ICounterService service)
        {
            _service = service;    
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult AddCounter([FromForm] BasicCounterData inputData)
        {
            if (ModelState.IsValid)
            {  
                var counter = new Counter{};
                counter.Title = inputData.Title;
                counter.Dimension = inputData.Dimension;
                counter.Color = inputData.Color;
                counter.Price = inputData.Price;
                counter.CreationDate = DateTime.Now;
                counter.UserId = inputData.UserId;

                _service.Create(counter);

                TempData["Success"] = $"Лічильник \"{counter.Title}\" було успішно додано";
            }
            else
            {
                TempData["Error"] = true;
            }

            return RedirectToAction("Index", "Dashboard");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult UpdateTitle([FromForm] UpdateTitleData inputData)
        {
            if (ModelState.IsValid)
            {   
                var counter = _service.GetById(inputData.CounterId);
                var oldTitle = counter.Title;
                counter.Title = inputData.Title;

                _service.Update(counter);

                TempData["Success"] = $"Назву лічильника \"{oldTitle}\" було успішно змінено";
            }
            else
            {
                TempData["Error"] = true;
            }
            return RedirectToAction("Index", "Dashboard");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult UpdateDimension([FromForm] UpdateDimensionData inputData)
        {
            if (ModelState.IsValid)
            {   
                var counter = _service.GetById(inputData.CounterId);
                counter.Dimension = inputData.Dimension;

                _service.Update(counter);
                
                TempData["Success"] = $"Одиницю вимірювання лічильника \"{counter.Title}\" було успішно змінено";
            }
            else
            {
                TempData["Error"] = true;
            }
            return RedirectToAction("Index", "Dashboard");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult UpdateColor([FromForm] UpdateColorData inputData)
        {
            if (ModelState.IsValid)
            {  
                var counter = _service.GetById(inputData.CounterId);
                counter.Color = inputData.Color;

                _service.Update(counter);
                
                TempData["Success"] = $"Колір лічильника \"{counter.Title}\" було успішно змінено";
            }
            else
            {
                TempData["Error"] = true;
            }

            return RedirectToAction("Index", "Dashboard");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult UpdatePrice([FromForm] UpdatePriceData inputData)
        {
            if (ModelState.IsValid)
            {  
                var counter = _service.GetById(inputData.CounterId);
                counter.Price = inputData.Price;

                _service.Update(counter);
                 
                TempData["Success"] = $"Вартість спожитої одиниці для \"{counter.Title}\" було успішно змінено";
            }
            else
            {
                TempData["Error"] = true;
            }

            return RedirectToAction("Index", "Dashboard");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete([FromForm] DeleteCounterData inputData)
        {
            if (ModelState.IsValid)
            {  
                var counter = _service.GetById(inputData.CounterId);

                _service.Delete(counter);
                
                TempData["Success"] = $"Лічильник \"{counter.Title}\" було успішно видалено";
            }
            else
            {
                TempData["Error"] = true;
            }

            return RedirectToAction("Index", "Dashboard");
        }
    }
}

Controllers/DashboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;
using Conum.Services;
using Conum.ViewModels;
using Conum.Data.Models;

namespace Conum.Controllers
{
    [Authorize]
    public class DashboardController : Controller
    {
        private ICounterService _counterService;
        private IRecordService _recordService;
        private readonly UserManager<User> _userManager;
        private readonly SignInManager<User> _signInManager;

        public User user;

        public DashboardController(
            ICounterService counterService,
            IRecordService recordService,
            SignInManager<User> signInManager,
            UserManager<User> userManager)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _counterService = counterService;
            _recordService = recordService;
        }

        [AllowAnonymous]
        public IActionResult Index()
        {
            user = _userManager.GetUserAsync(HttpContext.User).Result;
            if (user != null)
            {
                var userId = user.Id.ToString();
                user.Counters = _counterService.GetAllForUser(userId);
                if (user.Counters != null)
                {
                    Dictionary<long, decimal> recordsDifference = new Dictionary<long, decimal>();
                    
                    foreach (var counter in user.Counters)
                    {
                        counter.Records = _recordService.GetAllForCounter(counter.Id);
                        foreach (var record in counter.Records)
                        {
                            Record previousRecord = null;
                            decimal difference = 0;
                            
                            var recordsList = counter.Records.ToList();
                            for (int i = 0; i < recordsList.Count; i++)
                            {
                                if (recordsList[i].Id == record.Id)
                                {
                                    try
                                    {
                                        // Consider the desscending sort
                                        previousRecord = recordsList[i+1];
                                        difference = record.Value - previousRecord.Value;
                                    }
                                    catch
                                    {
                                    }
                                }
                            }
                            recordsDifference.Add(record.Id, difference);
                        }
                    } 
                    ViewBag.RecordsDifference = recordsDifference;
                }
            }

            ViewBag.User = user;

            return View();
        }

        public IActionResult ModalAddCounterAction()
        {
            ViewBag.UserId = _userManager.GetUserId(HttpContext.User);
            ViewBag.Email = _userManager.GetUserName(HttpContext.User);
            return PartialView("ModalAddCounter");
        }

        public IActionResult ModalDeleteRecordAction(long Id)
        {
            var record = _recordService.GetById(Id);
            ViewBag.Record = record;
            ViewBag.Counter = _counterService.GetById(record.CounterId);
            return PartialView("ModalDeleteRecord");
        }

        public IActionResult Error()
        {
            return View();
        }
    }
}

Controllers/RecordController.cs
using System;
using System.Globalization;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Conum.Services;
using Conum.ViewModels.Record;
using Conum.Data.Models;

namespace Conum.Controllers
{
    public class RecordController : Controller
    {
        private IRecordService _service;

        public RecordController(IRecordService service)
        {
            _service = service;
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult AddRecord([FromForm] AddRecordData inputData)
        {
            if (ModelState.IsValid)
            {  
                var record = new Record{};
                record.Value = inputData.Value;
                record.CreationDate = DateTime.ParseExact(inputData.CreationDate, "d/M/yyyy", CultureInfo.InvariantCulture);
                record.CounterId = inputData.CounterId;

                _service.Create(record);
                
                TempData["Success"] = "Новий показник було успішно додано";
            }
            else
            {
                TempData["Error"] = true;
            }

            return RedirectToAction("Index", "Dashboard");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteRecord([FromForm] DeleteRecordData inputData)
        {
            if (ModelState.IsValid)
            {  
                var record = _service.GetById(inputData.RecordId);

                _service.Delete(record);
                
                TempData["Success"] = "Обраний показник було успішно видалено";
            }
            else
            {
                TempData["Error"] = true;
            }

            return RedirectToAction("Index", "Dashboard");
        }
    }
}

Views/Dashboard/Index.cshtml
@using Microsoft.AspNetCore.Identity
@using Conum.Data.Models

@inject SignInManager<User> SignInManager
@inject UserManager<User> UserManager

@if (SignInManager.IsSignedIn(User))
{

<div class="row counters dashboard">
    @if (TempData["Success"] != null)
    {
        <div class="alert alert-success alert-dismissable fade in center-text">
            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
            @TempData["Success"]
        </div>
    }
    else if (TempData["Error"] != null)
    {
        <div class="alert alert-danger alert-dismissable fade in center-text">
            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
            <strong>Увага!</strong> Під час збереження даних сталася помилка. Будь ласка, перевірте зʼєднання та повторіть спробу.
        </div>
    }
    
    <div class="alert alert-warning alert-dismissable fade in center-text device-alert" style="display: none;">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        <strong>Увага!</strong> Мобільна версія не підтримує редагування лічильників.
    </div>
    @if (ViewBag.User.Counters != null)
    {
        @foreach (var counter in ViewBag.User.Counters)
        {
            <div class="col-sm-12 counter-nest">
                <div class="col-sm-3 center-text">
                    <span class="glyphicon glyphicon-ok-circle counter-icon" style="color: @counter.Color"></span>
                </div>

                <!-- General counter's info-->
                <div class="col-sm-5 counter-title h3">
                    <div class="col-sm-12 h3">
                        <span class="h3">Назва: @counter.Title</span>
                        <button type="button" class="btn btn-xs btn-info edit"
                            data-toggle="collapse"
                            data-counter="@counter.Id"
                            style="background-color: @counter.Color; border-color: @counter.Color"
                            data-target="#edit-for-@counter.Id">
                            Редагувати
                        </button>
                    </div>

                    <div class="col-sm-12">
                        <span>Одиниця вимірювання: </span>
                        <strong><span>@counter.Dimension</span></strong>
                    </div>
                    <div class="col-sm-12">
                        <span>Вартість спожитої одиниці: </span>
                        <strong><span>@counter.Price.ToString("G29")</span></strong>
                    </div>
                    @if (counter.Records.Count > 0)
                    {
                        <div class="col-sm-12">
                            <div>
                                <span>Останній запис має значення </span>
                                <strong><span clas>@counter.Records[0].Value.ToString("G29")</span></strong>
                            </div>
                            <div>
                                <span> Та актуальний станом на </span>
                                <strong><span> @counter.Records[0].CreationDate.ToString("dd/MM/yyyy")</span></strong>
                            </div>
                        </div>
                    }
                </div>
                <div class="col-sm-2">
                    <div class="button-wrapper text-center">
                        <button type="button" class="btn btn-info btn-sx all-records button-vertical-align" id="show-button-for-@counter.Id"
                            data-toggle="collapse"
                            data-target="#records-for-@counter.Id"
                            style="background-color: @counter.Color">
                            Показники</button>
                    </div>
                </div>

                <!-- Edit counter-->
                <div class="col-xs-12 collapse" id="edit-for-@counter.Id"}>
                    <div class="bs-component">
                        <ul class="nav nav-tabs">
                            <li class="active"><a href="#edit-title-for-@counter.Id" data-toggle="tab" aria-expanded="true">Назва</a></li>
                            <li class=""><a href="#edit-dimension-for-@counter.Id" data-toggle="tab" aria-expanded="false">Одиниця вимірювання</a></li>
                            <li class=""><a href="#edit-price-for-@counter.Id" data-toggle="tab" aria-expanded="false">Вартість спожитої одиниці</a></li>
                            <li class=""><a href="#edit-color-for-@counter.Id" data-toggle="tab" aria-expanded="false">Колір</a></li>
                            <li class=""><a href="#delete-@counter.Id" data-toggle="tab" aria-expanded="false">Видалення</a></li>
                            
                        
                        </ul>
                        <div class="tab-content">
                            <div class="tab-pane fade active in" id="edit-title-for-@counter.Id">
                                @Html.Partial("/Views/Partial/Counter/UpdateCounterTitle.cshtml",
                                new ViewDataDictionary(ViewData) { { "CounterId", counter.Id } })
                            </div>
                            <div class="tab-pane fade" id="edit-dimension-for-@counter.Id">
                                @Html.Partial("/Views/Partial/Counter/UpdateCounterDimension.cshtml",
                                new ViewDataDictionary(ViewData) { { "CounterId", counter.Id } })
                            </div>
                            <div class="tab-pane fade" id="edit-price-for-@counter.Id">
                                @Html.Partial("/Views/Partial/Counter/UpdateCounterPrice.cshtml",
                                new ViewDataDictionary(ViewData) { { "CounterId", counter.Id } })
                            </div>
                            <div class="tab-pane fade" id="edit-color-for-@counter.Id">
                                @Html.Partial("/Views/Partial/Counter/UpdateCounterColor.cshtml",
                                new ViewDataDictionary(ViewData) { { "CounterId", counter.Id }, {"CounterColor", counter.Color} })
                            </div>
                            <div class="tab-pane fade" id="delete-@counter.Id">
                                @Html.Partial("/Views/Partial/Counter/DeleteCounter.cshtml",
                                new ViewDataDictionary(ViewData) { { "CounterId", counter.Id }, {"CounterTitle", counter.Title}})
                            </div>
                        </div>
                    </div>
                </div>

                <!-- Records list-->
                    <div id="records-for-@counter.Id" data-counter="@counter.Id" class="col-sm-12 collapse center-text records-nest">
                        <div class="bs-component">
                            <ul class="nav nav-tabs">
                                <li class="active"><a href="#records-list-for-@counter.Id" data-toggle="tab" aria-expanded="true">Список</a></li>
                                <li class=""><a href="#add-new-record-for-@counter.Id" data-toggle="tab" aria-expanded="false">Додати новий показник</a></li>     
                            </ul>
                            <div class="tab-content">
                                <div class="tab-pane fade active in records-inner-nest" id="records-list-for-@counter.Id">
                                    <!-- Foreach records -->
                                    @if (counter.Records.Count < 1)
                                    {
                                        <p>Ви не додали жодного показника для цього лічильника</p>
                                    }
                                    else
                                    {
                                        if (counter.Records.Count < 5)
                                        {
                                            <p>Діаграма споживання для обраного лічильника зʼявиться після внесення більшої кількості показників</p>
                                        }
                                        else
                                        {
                                            <canvas id="records-chart-for-@counter.Id"></canvas>
                                        }
                                        <table class="table table-striped table-hover records-table-for-@counter.Id">
                                            <thead>
                                                <tr>
                                                    <th>Дата</th>
                                                    <th>Показники</th>
                                                    <th>Спожито за період</th>
                                                    <th>Вартість спожитого</th>
                                                    <th></th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                            @foreach(var record in counter.Records)
                                            {
                                                <tr>
                                                    <td class="record-creation-date">@record.CreationDate.ToString("dd/MM/yyyy")</td>
                                                    <td class="record-value">@record.Value.ToString("G29")</td>
                                                    <td class="record-spent">@ViewBag.RecordsDifference[record.Id].ToString("G29")</td>
                                                    <td class="record-spent-price">@((counter.Price * ViewBag.RecordsDifference[record.Id]).ToString("#,#.##"))</td>
                                                    <td>
                                                        <a asp-action="ModalDeleteRecordAction" asp-controller="Dashboard" asp-route-id="@record.Id" data-target="#delete-record-modal-container" data-toggle="modal">
                                                            <span class="glyphicon glyphicon-remove-circle" style="color: red"></span>
                                                        </a>
                                                    </td>
                                                </tr>
                                            } 
                                            </tbody>
                                        </table>
                                    }
                                    
                                </div>
                                <div id="add-new-record-for-@counter.Id" class="tab-pane fade">
                                    @Html.Partial("/Views/Partial/Record/AddRecord.cshtml",
                                    new ViewDataDictionary(ViewData) {{ "CounterId", counter.Id }})   
                                </div>
                            </div>
                        </div>
                        
                        <div class="col-sm-12 counter-nest-bottom"></div>
                    </div>
            </div>

            <div id="delete-record-modal-container" class="modal fade hidden-print" tabindex="-1" role="dialog">
                <div class="modal-dialog">
                    <div class="modal-content">
                    </div>
                </div>
            </div>
        }
    }
    else
    {
        <div class="intro">
            <div class ="col-xs-12 center-text">
                <p>Вітаємо! Ви успішно створили обілковий запис в <strong>Conum</strong>. Додайте свій перший лічильник та заповніть його показниками, аби побачити всі можливості цього web-застосунку.</p>
                <p>Не варто надто хвилюватися з приводу введених даних при створенні лічильника. Ви все зможете оновити пізніше.</p>
            </div>
        </div>
        
    }
    <div id="add-counter-modal-container" class="modal fade hidden-print" tabindex="-1" role="dialog">
        <div class="modal-dialog">
            <div class="modal-content">
            </div>
        </div>
    </div>
</div>
}
else
{
    <div class="intro">
        <div class="col-xs-12">
            <p><strong>Conum</strong> навіть назвою побудований з двох частин: <strong>counters</strong> (лічильники) та <strong>numbers</strong> (показники). Це простий web-застосунок, що дозволяє зберігати показники будь-якого типу лічильників та аналізувати вартість та історію споживання вимірюваних ресурсів.</p>
            <p>Опісля занесення даних ви зможете аналізувати їх за допомогою діаграми споживання та зручної підрахункової таблиці, що автоматично рахує для вас вартість використаних ресурсів.</p>
            <p>Легка в розумінні оболонка програми та спеціальний підхід до візуального маркування лічильників допоможуть вам без зайвих зусиль тримати показники в належному стані.</p>
        </div>
        <div class ="col-xs-12 center-text text-muted creds">
            <p>Розробка, підтримка та зворотній звʼязок: weareua@gmail.com</p>
        </div>
        <div class ="col-xs-12">
            <img id="diagram" class="center-block" src="../images/index-diagram.jpg">
        </div>
    </div>
    
}

Views/Dashboard/ModalAddCounter.cshtml
@model Conum.ViewModels.Counter.BasicCounterData

@* Here is the content for the modal*@
<div id="target">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        <h4 class="modal-title">Додати Лічильник</h4>
    </div>
    
    <form asp-action="AddCounter" asp-controller="Counter" method="post" id="add-counter-form">
        <div class="modal-body">
            <div class="form-horizontal">
                <div class="form-group row">
                    <div class="col-sm-12">
                        <input class="form-control" asp-for="Title" type="text" placeholder="Введіть назву лічильника" id="title-input" required>
                    </div>
                    <div class="col-sm-12">
                        <input class="form-control" asp-for="Dimension" type="text" placeholder="Введіть одиницю вимірювання" id="dimension-input" required>
                    </div>
                    <div class="col-sm-12">
                        <input id="pick-color" asp-for="Color" type="text" placeholder="Оберіть колір" class="form-control" required/>
                    </div>
                    <div class="col-sm-12">
                        <input asp-for="Price" type="number" step="0.001" placeholder="Вкажіть вартість одиниці (цифри)" class="form-control" required/>
                    </div>
                        <input class="form-control" asp-for="UserId" type="hidden" value=@ViewBag.UserId>
                </div>
            </div>
        </div>
        <div class="modal-footer">
            <button type="submit" class="btn btn-warning">Додати</button>
            <button type="button" class="btn btn-danger" data-dismiss="modal">Скасувати</button>
        </div>
    </form>
</div>

<script>
$(document).ready(function(){
    $('#pick-color').colorpicker({
        format: 'hex'
    });

$('#add-counter-form').validator();
});
</script>

Views/Dashboard/ModalDeleteRecord.cshtml
@model Conum.ViewModels.Record.DeleteRecordData

@* Here is the content for the modal*@
<div id="target">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        <h4 class="modal-title">Видалити Запис</h4>
    </div>
    
    <form asp-action="DeleteRecord" asp-controller="Record" method="post">
        <div class="modal-body">
            <div class="form-horizontal">
                <div class="form-group row">
                    <p>Видалити обраний запис, створений @ViewBag.Record.CreationDate.ToString("dd/MM/yyyy") для лічильника @ViewBag.Counter.Title?</p>
                    <input class="form-control" asp-for="RecordId" type="hidden" value=@ViewBag.Record.Id>
                </div>
            </div>
        </div>
        <div class="modal-footer">
            <button type="submit" class="btn btn-warning">Видалити</button>
            <button type="button" class="btn btn-danger" data-dismiss="modal">Скасувати</button>
        </div>
    </form>
</div>